package org.paginalibre.dao.impl;
import java.sql.*; import java.util.*; import org.paginalibre.dao.ProveedorDAO; import org.paginalibre.model.Proveedor; import org.paginalibre.util.Conexion;
public class ProveedorDAOImpl implements ProveedorDAO {
 public boolean insertar(Proveedor v){String s="INSERT INTO proveedores(nombre_proveedor,telefono_proveedor,direccion_proveedor,correo_proveedor) VALUES(?,?,?,?)";try(Connection x=Conexion.getInstancia().conectar();PreparedStatement p=x.prepareStatement(s)){p.setString(1,v.getNombre());p.setString(2,v.getTelefono());p.setString(3,v.getDireccion());p.setString(4,v.getCorreo());return p.executeUpdate()>0;}catch(SQLException e){return false;}}
 public List<Proveedor> listar(){List<Proveedor> r=new ArrayList<>();String s="SELECT id_proveedor,nombre_proveedor,telefono_proveedor,direccion_proveedor,correo_proveedor FROM proveedores ORDER BY nombre_proveedor";try(Connection x=Conexion.getInstancia().conectar();PreparedStatement p=x.prepareStatement(s);ResultSet q=p.executeQuery()){while(q.next())r.add(map(q));}catch(SQLException e){}return r;}
 public Proveedor buscar(Integer id){String s="SELECT id_proveedor,nombre_proveedor,telefono_proveedor,direccion_proveedor,correo_proveedor FROM proveedores WHERE id_proveedor=?";try(Connection x=Conexion.getInstancia().conectar();PreparedStatement p=x.prepareStatement(s)){p.setInt(1,id);try(ResultSet q=p.executeQuery()){return q.next()?map(q):null;}}catch(SQLException e){return null;}}
 public boolean actualizar(Proveedor v){String s="UPDATE proveedores SET nombre_proveedor=?,telefono_proveedor=?,direccion_proveedor=?,correo_proveedor=? WHERE id_proveedor=?";try(Connection x=Conexion.getInstancia().conectar();PreparedStatement p=x.prepareStatement(s)){p.setString(1,v.getNombre());p.setString(2,v.getTelefono());p.setString(3,v.getDireccion());p.setString(4,v.getCorreo());p.setInt(5,v.getId());return p.executeUpdate()>0;}catch(SQLException e){return false;}}
 public boolean eliminar(Integer id){String s="DELETE FROM proveedores WHERE id_proveedor=?";try(Connection x=Conexion.getInstancia().conectar();PreparedStatement p=x.prepareStatement(s)){p.setInt(1,id);return p.executeUpdate()>0;}catch(SQLException e){return false;}}
 private Proveedor map(ResultSet q)throws SQLException{return new Proveedor(q.getInt(1),q.getString(2),q.getString(3),q.getString(4),q.getString(5));}
}
